---
title: "Convivencia"
author: " "
date: " "
output:
  html_document:
    toc: no
    toc_depth: 2
    toc_float: yes
    theme: cerulean
css: _style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

LAUDES : Segun la liturgia de las horas -ver ordo

1. Monición ambiental
2. Invitatorio : 
  * Señor abre mis labios ...
  * Y mi boca proclamará tu alabanza ...
3. Oración (Presbítero o quien preside o responsable) 
4. Salmo 94 - Si hoy escuchais su voz (141) 

5. SALMODIA
  * Antifona 1 / Salmo  / Gloria al Padre, al Hijo y al Espíritu santo .../ Antifona 1
  * Antifona 2 / Salmo  / Gloria al Padre, al Hijo y al Espíritu santo .../ Antifona 2 
  * Antifona 3 / Salmo  / Gloria al Padre, al Hijo y al Espíritu santo .../ Antifona 3

**Nota** 

* En caso de no ser un salmo no se dice el Gloria  
* Si el salmo no es un canto, se proclama

6. Lectura kerigmatica
* 30 minutos escrutacio - escrutar : leer - escrutar - reflexionar
7. Antifona - Cantico evangélico Benedictus (47) - Gloria al Padre, al Hijo y al Espíritu santo- Antifona de acuerdo al año litúrgico 
8. Oraciones
9. Padre nuestro
10. Saludo de paz
11. Bendición final
12. Almuerzo - compartir 
  * Todos empezamos juntos - canto de oración del almuerzo
13. Giros de experiencia
  * Cómo te ha ayudado la palabra en este tiempo?
  * Tienes algo sobre un hermano de comunidad? - pedir perdón - abrazo
14. Grupos de preparación -
15. Colecta de gastos y signos - bolsa - contar - informar a la comunidad
16. Informe de gastos
17. Oraciones
18. Padre nuestro
19. Saludo de paz
20. Canto Magnificat (101)
21. Bendición final

  
  