---
title: "Eucaristia"
output:
  html_document:
    toc: no
    toc_depth: 2
    toc_float: yes
    theme: cerulean
css: _style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

</br></br>

### **RITOS INICIALES**

1. Monición inicial :

2. Canto de entrada :

3. Acto penitencial

4. Gloria a Dios

5. Oración

</br>

**LITURGIA DE LA PALABRA**

6. Monición primera lectura
7. Primera lectura

8. Salmo responsorial

9. Monición segunda lectura
10. Segunda lectura

11. Monición al evangelio
12. Aleluya - antifona evangelio
13. Evangelio

14. Ecos

15. Homilia

16. Proclamación de la fé

17. Oraciones universales
  * Te pedimos Señor por la **IGLESIA** ... .... para que ... ...
  * Te pedimos Señor por los **GOBERNANTES** ... ... para que ... ...
  * Te pedimos Señor por los **QUE SUFREN** ... ...  para que ... ...
  * Te pedimos Señor por las **COMUNIDADES** ... ... para que ... ...


18. Saludo de la paz

19. Se sirve la mesa : Corporal - pan, vino, calis

</br>

**LITURGIA DE LA EUCARISTIA**


20. Presentación de los dones
21. Gran oración eucarística _ Prefacio, Sanctus, Plegaria eucarística - cantada 
22. Oración del Padre nuestro
22. El signo de la fracción del Pan (con elevación, mostrandolo a la asamblea)
23. El signo de la comunión - comunión sacramental sentados, bajo las dos especies 
* Se hacen cantos correspondienes  
* Entrega del Cuerpo de Cristo a los hermanos - reciben un trozo de pan ácimo en la mano derecha y poniendo la izquierda sobre ella  
* Una vez distribuida la comunión del Cuerpo de Cristo, el Sacerdote desde la sede, sentado, presenta el Cuerpo de Cristo como el Cordero de Dios que quita el pecado del mundo y pone de manifiesto la dicha por estar invitados a la Cena del Señor
La Asamblea responde Amen y todos comulgan al mismo tiempo.
* Para la comunión de la Sangre del Señor se actúa del mismo modo que para el 
Cuerpo de Cristo.

</br>

**RITO DE CONCLUSIÓN**

24. Oración final
25. Canto final y dfanza al rededor del altar 
26. Avisos responsable

</br>

**Nota**: 

* Al pasar al atril se hace la venia al sacerdote, de regreso no se hace venia
* Se toma el vino por un angulo del calis
* Al finalizar cada una de las oración universal no se dice te lo pedimos Señor, lo hace el salmista







