---
title: "Palabra"
author: " "
date: " "
output:
  html_document:
    toc: no
    toc_depth: 2
    toc_float: yes
    theme: cerulean
css: _style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **Celebración**

</br>

1. Monición ambiental
2. Canto de entrada
3. Oración responsable
4. Invocación al Espiritu Santo : 
* Oracion espontanea.....
* Te lo pedimos invocando tu Santo Espiritu:
  * Oh Señor envía tu espiritu, que renueve la faz de la tierra (Bis)

</br>

5. Monición primera lectura
6. Primera lectura
7. Canto respuesta a la primera lectura

</br>

8. Monición segunda lectura
9. Segunda lectura
10. Canto respuesta a la segunda lectura

</br>

11. Monición tercera lectura
12. Tercera lectura
13. Canto respuesta a la tercera lectura

</br>

14. Monición al evangelio 
15. Evangelio - proclama responsable

</br>

16. Ecos de la palabra : Lo que te dice la palabra recibida - primera persona

</br>

17. Homilia, solo si preside un Sacerdote

18. Oraciones 
* empieza con la oración por los hermanos en lista en la biblia de Jerusalén que no asistieron.
* en primera persona, manos extendidas 
  * Te pido Señor .... R/A: Te lo pedimos Señor
  * Te doy gracias ....R/A: Te damos gracias Señor

* Te entregamos nuestras oraciones y te lo pedimos diciendo ....  

19. Padre nuestro
20. Saludo de Paz 
* Los invito a darnos el beso y el abrazo de la Paz
21. Canto final
22. Bendición final
* (Sacerdonte/Responsable) El Señor nos bendiga, nod guarde de todo mal y nos lleve a la vida eterna, Amen.

</br>

23. Avisos por parte del responsable


Nota : 

* La palabra se lee de la Biblia de Jerusalen grande

