---
title: "**Celebraciones de Temas**"
author: " "
date: " "
output: 
  html_document:
    css: _style.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

</br></br>

###  **TEMAS / EQUIPOS**

</br></br>

#### **1. ABRAHAM**

Equipo : Oneida, Carmen Edith, Carlos Alberto, Maria Graciela

</br></br>

#### **2. EXODO (hasta la llegada al desierto)**

Equipo: Gerardo, Marlene, Amparo, Maria del Carmen, Yolanda

</br></br>


#### **3. ALIANZA del Sinaí**

Equipo: Daniel, Adriana, Laura, Marlene A, Yolanda

</br></br>

#### **4. CAMINO POR EL DESIERTO**

**Equipo**: Jhon Michel, Maruja, Carmen Zoraida, Miroslava, Karen

</br></br>

#### **5. CONQUISTA DE LA TIERRA PROMETIDA (Josué)**

**Equipo**: Oneida, Amparo, Carmen Edith, Gerardo, Marleny

</br></br>


#### **6. DAVID Y EL REINO**

**Equipo**: Yolanda, Marlene, Adriana, Daniel

</br></br>


#### **7. EXILIO**

**Equipo**: Carlos Hernan, Zoraida, Tomas, Miroslava

Fechas:

* 1. Junio 18: Celebración Palabra
* 2. Junio 25: Catequesis
* 3. Julio 2 : Celebración doméstica
* 4. Julio 9 : Celebración de palabra
* 5. Julio 14: Conviviencia 

</br></br>


#### **8. PROFETAS**

**Equipo**: Maria Graciela, Maria del Carmen, Oneida, Karen, Amparo

</br></br>


#### **9. LOS ORÍGENES (la creación, el mal y el pecado)**

**Equipo**: Jhon Michel, Gerardo, Marlene, Carmen Zoraida, Yolanda

</br></br></br></br>

#### 10. EL MESÍAS

**Equipo**:

</br></br>



#### **11. LA RESURRECCIÓN**

**Equipo**:

</br></br>

#### **12. LA IGLESIA (sacramentos de salvación)**

**Equipo**:

</br></br>

#### **13. LA IGLESIA PRIMITIVA (los primeros tres siglos)**

**Equipo**:

</br></br>

#### **14. LA IGLESIA DE CONSTANTINO HASTA EL CONCILIO DE TRENTO**


**Equipo**:

</br></br>


#### **15. LA IGLESIA DEL CONCILIO DE TRENTO AL VATICANO II**

Equipo:

</br></br>


#### **16. EL CONCILIO VATICANO II**

**Equipo**:

</br></br>


#### **17. LA PERUSÍA**

**Equipo**:

</br></br>

