---
title: "VIERNES SANTO"
output:
  html_document:
    toc: no
    toc_depth: 2
    toc_float: yes
    theme: cerulean
css: _style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

Adoracion a la cruz

Este dia no hay flores

Se emplea : la cruz, purificador, atril, cubri atril **rojo**, dos velones, un cojin rojo, 

</br></br>

### CELEBRACIÓN

<br/>

##### MONICIÓN AMBIENTAL

* No hay canto

<br/>

##### ORACIÓN

<br/>

##### INVOCACIÓN AL ESPIRITU SANTO

</br>

##### PRIMERA LECTURA

* Monición primera lectura
* Primera lectura : Is 52, 13-15; 53, 1-12 (proclama Miroslava)
* Canto : ELI, ELI LAMÁ SABACTANÍ - 70, Salmista: Carlos 

</br>

##### SEGUNDA LECTURA

* Monición segunda lectura
* Segunda lectura: Hb 4, 14-16; 5, 7-9 (proclama Carmen Edith)
* Canto : DICE EL SEÑOR A MI SEÑOR - 64, Salmista: Tomás 

</br>

##### TERCERA LECTURA

* Monición tercera lectura
* Tercera lectura (Responsable) : Jn 18, 1-40; 19, 1-42 (proclama Daniel)


Cuando se lea : **E inclinó la cabeza entregó el espiritu...** (Todos se arodillan y se hace una pausa)

<br/>

##### ECOS - HOMILIA (en caso que presida un sacerdote)

<br/>

##### ORACIONES UNIVERSALES - Misal

<br/>

##### ADORACIÓN A LA SANTA CRUZ 

* Responsable más dos hermanos :  Desde la puerta toma la cruz y 2 velones encendidas a lado y lado.

* Procesión de la cruz (camina - pare) : 
  * R: **Mirad el árbol de la cruz donde estuvo clavada la salvación de este mundo**, 
  * A: **Venid adorarla**.


* Se situa la cruz para su adoración : Adoración de la cruz : Es un momento, se puede arrodillar, besar y contemplar. Se limpia con un purificador después del beso.


### CANTOS

* HIMNO A LA CRUZ GLORIOSA - 219, Salmista: Marleny
* IMPROPERIOS - 93, Salmista: Daniel
* OH JESUS AMOR MIO - 116, Salmista: Tomás 
* HIJAS DE JERUSALEM - 86, Salmista: Marleny 
* OH DIOS, TU ERES MI DIOS - 115, Salmista: Tomas
* COMO OVEJA QUE VE COMO SE LLEVAN SU CORDERITO AL MATADERO - 166-1, Salmista: Daniel
* SOLO A SOLO - 144, Salmista: Daniel 
* MARIA MADRE DEL IGLESIA - 104, Salmista: Marleny


<br/>

##### BENDICIÓN

* No hay paz
* Se promulga el ayuno.  
* El sábado : almuerzo con la palabra. Hora : 12 m

<br/>

Colecta de gastos para la Pascua

<br/><br/>

##### GRUPOS SABADO SANTO:

##### GRUPO 1

* Daniel
* Adriana
* Carmen Edith
* Carlos Alberto
* Amparo
* Karen
* Jhon Michel

##### GRUPO 2

* Gerardo
* Marlene
* Carmen Zoraida
* Yolanda
* Marlene Asprilla
* Maria Graciela


##### GRUPO 3

* Oneida
* Maruja
* Miroslava
* Tomas
* Maria del Carmen
* Carlos Hernan
* Zoraida Duque



##### Nota:

Se nos pide ayudar a armar la asamblea en el hotel Dann el sábado en la mañana y tambien apoyar lo relacionado con el arreglo de flores y el llenado de la pila bautismal.

Sábado a las 9:00 am




